### ISSUE TITLE
Moon phase not showing

### ISSUE THREAD

**Issue by hukoeth** [r-renato/ha-card-weather-conditions#10]
Hi Renato,
I love this card, thanks so much for it. This morning I noticed that the card stayed blank but was delighted to see that an update fixing this bug (#9 ) was already waiting.
I updated the card, cleared cache and now the card is showing correctly however the moon phase is no longer visible on the card.
Any ideas or any troubleshooting I could do?
Thanks,
Uli

**Comment by r-renato** [comment]
Hi,
check your browser console and put here the logs.

**Comment by hukoeth** [comment]
Hey, sorry this was my bad. First time when I configured the card I copy-pasted the example yaml from readme. This time I used the table where there was a typo (moon instead of moon_phase). Anyway I created a pull request to fix this and also add german language if you're interested.
Thanks for your quick reply
