### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by drmilos** [r-renato/ha-card-weather-conditions#15]
Hi I would help with translation to Serbian language.

How I can do it?

**Comment by r-renato** [comment]
Hi, thanks for your support. To add the Serbian translation you need to modify the following structures:

```
export let cwcLocale = {en: 0, it: 1, nl: 2, es: 3, de: 4, fr: 5};

export let cwcLocWindDirections = {
  'N': ['N', 'N', 'N', 'N', 'N', 'N'],
  'NNE': ['NNE', 'NNE', 'NNO', 'NNE', 'NNO', 'NNE'],
  'NE': ['NE', 'NE', 'NO', 'NE', 'NO', 'NE'],
  'ENE': ['ENE', 'ENE', 'ONO', 'ENE', 'ONO', 'ENE'],
  'E': ['E', 'E', 'O', 'E', 'O', 'E'],
  'ESE': ['ESE', 'ESE', 'OZO', 'ESE', 'OSO', 'ESE'],
  'SE': ['SE', 'SE', 'ZO', 'SE', 'SO', 'SE'],
  'SSE': ['SSE', 'SSE', 'ZZO', 'SSE', 'SSO', 'SSE'],
  'S': ['S', 'S', 'Z', 'S', 'S', 'S'],
  'SSW': ['SSW', 'SSO', 'ZZW', 'SSO', 'SSW', 'SSO'],
  'SW': ['SW', 'SO', 'ZW', 'SO', 'SW', 'SO'],
  'WSW': ['WSW', 'OSO', 'WZW', 'OSO', 'WSW', 'OSO'],
  'W': ['W', 'O', 'W', 'O', 'W', 'O'],
  'WNW': ['WNW', 'ONO', 'WNW', 'ONO', 'WNW', 'ONO'],
  'NW': ['NW', 'NO', 'NW', 'NO', 'NW', 'NO'],
  'NNW': ['NNW', 'NNO', 'NNW', 'NNO', 'NNW', 'NNO'],
};

export let cwcTerms = {
  'Feels Like' : ['Feels Like', 'Percepita', 'Voelt Als', 'Parece que', 'Gef&uuml;hlt', 'Ressentie'],
  'new_moon': [ 'New moon', 'Novilunio', 'Nieuwe maan', 'Luna nueva', 'Neumond', 'Nouvelle lune'],
  'new': [ 'New moon', 'Novilunio', 'Nieuwe maan', 'Luna nueva', 'Neumond', 'Nouvelle lune'],
  'waxing_crescent': ['Waxing crescent', 'Luna crescente', 'Wassende sikkel', 'Media luna de cera', 'Zunehmende Sichel', 'Premier croissant'],
  'first_quarter': ['First quarter', 'Primo Quarto', 'Eerste kwartaal', 'Primer trimestre', 'Erstes Viertel', 'Premier quartier'],
  'waxing_gibbous': ['Waxing Gibbous', 'Gibbosa crescente', 'Wassen Gibbous', 'Encerado Gibbous', 'Zunehmender Halbmond', 'Gibbeuse croissante'],
  'full': ['Full', 'Luna piena', 'Volledig', 'Completo', 'Vollmond', 'Pleine lune'],
  'waning_gibbous': ['Waning Gibbous', 'Gibbosa calante', 'Zwemmende Gibbous', 'Waning Gibbous', 'Abnehmender Halbmond', 'Gibbeuse décroissante'],
  'third_quarter': ['Third Quarter', 'Ultimo quarto', 'Derde Kwartier', 'Tercer cuarto', 'Drittes Viertel', 'Dernier quartier'],
  'last_quarter': ['Last Quarter', 'Ultimo quarto', 'Laatste Kwartier', 'Último cuarto', 'Letztes Viertel', 'Dernier quartier'],
  'waning_crescent': ['Waning Crescent', 'Luna calante', 'Zwemmende sikkel', 'Waning Crescent', 'Abnehmende Sichel', 'Lune décroissante'],
} ;
```
Put here the modified structures  and I will update the code.

Thanks, Renato

**Comment by drmilos** [comment]
Done!

`export let cwcLocale = {en: 0, it: 1, nl: 2, es: 3, de: 4, fr: 5, sr: 6};

export let cwcLocWindDirections = {
  'N': ['N', 'N', 'N', 'N', 'N', 'N', 'S'],
  'NNE': ['NNE', 'NNE', 'NNO', 'NNE', 'NNO', 'NNE', 'SSI'],
  'NE': ['NE', 'NE', 'NO', 'NE', 'NO', 'NE', 'SI'],
  'ENE': ['ENE', 'ENE', 'ONO', 'ENE', 'ONO', 'ENE', 'ISI'],
  'E': ['E', 'E', 'O', 'E', 'O', 'E', 'I'],
  'ESE': ['ESE', 'ESE', 'OZO', 'ESE', 'OSO', 'ESE', 'IJI'],
  'SE': ['SE', 'SE', 'ZO', 'SE', 'SO', 'SE', 'JI'],
  'SSE': ['SSE', 'SSE', 'ZZO', 'SSE', 'SSO', 'SSE', 'JJI'],
  'S': ['S', 'S', 'Z', 'S', 'S', 'S', 'J'],
  'SSW': ['SSW', 'SSO', 'ZZW', 'SSO', 'SSW', 'SSO', 'JJZ'],
  'SW': ['SW', 'SO', 'ZW', 'SO', 'SW', 'SO', 'JZ'],
  'WSW': ['WSW', 'OSO', 'WZW', 'OSO', 'WSW', 'OSO', 'ZSZ'],
  'W': ['W', 'O', 'W', 'O', 'W', 'O', 'Z'],
  'WNW': ['WNW', 'ONO', 'WNW', 'ONO', 'WNW', 'ONO', 'ZSZ'],
  'NW': ['NW', 'NO', 'NW', 'NO', 'NW', 'NO', 'SZ'],
  'NNW': ['NNW', 'NNO', 'NNW', 'NNO', 'NNW', 'NNO', 'SSZ'],
};

export let cwcTerms = {
  'Feels Like' : ['Feels Like', 'Percepita', 'Voelt Als', 'Parece que', 'Gef&uuml;hlt', 'Ressentie', 'Subjektivni osećaj'],
  'new_moon': [ 'New moon', 'Novilunio', 'Nieuwe maan', 'Luna nueva', 'Neumond', 'Nouvelle lune', 'Mlad mesec'],
  'new': [ 'New moon', 'Novilunio', 'Nieuwe maan', 'Luna nueva', 'Neumond', 'Nouvelle lune', 'Mlad mesec'],
  'waxing_crescent': ['Waxing crescent', 'Luna crescente', 'Wassende sikkel', 'Media luna de cera', 'Zunehmende Sichel', 'Premier croissant', 'Premier croissant', 'Prva osmina'],
  'first_quarter': ['First quarter', 'Primo Quarto', 'Eerste kwartaal', 'Primer trimestre', 'Erstes Viertel', 'Premier quartier', 'Prva četvrt'],
  'waxing_gibbous': ['Waxing Gibbous', 'Gibbosa crescente', 'Wassen Gibbous', 'Encerado Gibbous', 'Zunehmender Halbmond', 'Gibbeuse croissante', 'Treća osmina'],
  'full': ['Full', 'Luna piena', 'Volledig', 'Completo', 'Vollmond', 'Pleine lune', 'Pun mesec'],
  'waning_gibbous': ['Waning Gibbous', 'Gibbosa calante', 'Zwemmende Gibbous', 'Waning Gibbous', 'Abnehmender Halbmond', 'Gibbeuse décroissante', 'Peta osmina'],
  'third_quarter': ['Third Quarter', 'Ultimo quarto', 'Derde Kwartier', 'Tercer cuarto', 'Drittes Viertel', 'Dernier quartier', 'Treća četvrtina'],
  'last_quarter': ['Last Quarter', 'Ultimo quarto', 'Laatste Kwartier', 'Último cuarto', 'Letztes Viertel', 'Dernier quartier', 'Zadnja četvrtina'],
  'waning_crescent': ['Waning Crescent', 'Luna calante', 'Zwemmende sikkel', 'Waning Crescent', 'Abnehmende Sichel', 'Lune décroissante', 'Sedma osmina'],
} ;`

**Comment by bsrdjan** [comment]
Serbian language has a Latin and Cyrillic alphabets

For latin translation the language code subtag shall be `sr-Latn`, referring to https://en.wikipedia.org/wiki/ISO_15924, and `sr-Cyrl` can be added as well. 

Would it make sense to capitalise only the first letter of weekday names (lowercase from 2nd letter) ?

**Comment by r-renato** [comment]
> Serbian language has a Latin and Cyrillic alphabets
> 
> For latin translation the language code subtag shall be `sr-Latn`, referring to https://en.wikipedia.org/wiki/ISO_15924. `sr-Cyrl` can be added as well.
> 
> Would it make sense to capitalise only the first letter of weekday names (lowercase from 2nd letter) ?

Thanks for your suggestion, it's been very useful to me.
To capitalize the name of the days of the week you can change the css class 
```
- type: custom:ha-card-weather-conditions
  style: |
    .dayname {
      text-transform: capitalize;
    }
```

Thank you, 
Renato

**Comment by r-renato** [comment]
> Done!
> 
> Don't know how to embed code and hope you can use it as posted.
> 
> `
> export let cwcLocale = {en: 0, it: 1, nl: 2, es: 3, de: 4, fr: 5, sr: 6};
> 
> export let cwcLocWindDirections = {
> 'N': ['N', 'N', 'N', 'N', 'N', 'N', 'S'],
> 'NNE': ['NNE', 'NNE', 'NNO', 'NNE', 'NNO', 'NNE', 'SSI'],
> 'NE': ['NE', 'NE', 'NO', 'NE', 'NO', 'NE', 'SI'],
> 'ENE': ['ENE', 'ENE', 'ONO', 'ENE', 'ONO', 'ENE', 'ISI'],
> 'E': ['E', 'E', 'O', 'E', 'O', 'E', 'I'],
> 'ESE': ['ESE', 'ESE', 'OZO', 'ESE', 'OSO', 'ESE', 'IJI'],
> 'SE': ['SE', 'SE', 'ZO', 'SE', 'SO', 'SE', 'JI'],
> 'SSE': ['SSE', 'SSE', 'ZZO', 'SSE', 'SSO', 'SSE', 'JJI'],
> 'S': ['S', 'S', 'Z', 'S', 'S', 'S', 'J'],
> 'SSW': ['SSW', 'SSO', 'ZZW', 'SSO', 'SSW', 'SSO', 'JJZ'],
> 'SW': ['SW', 'SO', 'ZW', 'SO', 'SW', 'SO', 'JZ'],
> 'WSW': ['WSW', 'OSO', 'WZW', 'OSO', 'WSW', 'OSO', 'ZSZ'],
> 'W': ['W', 'O', 'W', 'O', 'W', 'O', 'Z'],
> 'WNW': ['WNW', 'ONO', 'WNW', 'ONO', 'WNW', 'ONO', 'ZSZ'],
> 'NW': ['NW', 'NO', 'NW', 'NO', 'NW', 'NO', 'SZ'],
> 'NNW': ['NNW', 'NNO', 'NNW', 'NNO', 'NNW', 'NNO', 'SSZ'],
> };
> 
> export let cwcTerms = {
> 'Feels Like' : ['Feels Like', 'Percepita', 'Voelt Als', 'Parece que', 'Gefühlt', 'Ressentie', 'Subjektivni osećaj'],
> 'new_moon': [ 'New moon', 'Novilunio', 'Nieuwe maan', 'Luna nueva', 'Neumond', 'Nouvelle lune', 'Mlad mesec'],
> 'new': [ 'New moon', 'Novilunio', 'Nieuwe maan', 'Luna nueva', 'Neumond', 'Nouvelle lune', 'Mlad mesec'],
> 'waxing_crescent': ['Waxing crescent', 'Luna crescente', 'Wassende sikkel', 'Media luna de cera', 'Zunehmende Sichel', 'Premier croissant', 'Premier croissant', 'Prva osmina'],
> 'first_quarter': ['First quarter', 'Primo Quarto', 'Eerste kwartaal', 'Primer trimestre', 'Erstes Viertel', 'Premier quartier', 'Prva četvrt'],
> 'waxing_gibbous': ['Waxing Gibbous', 'Gibbosa crescente', 'Wassen Gibbous', 'Encerado Gibbous', 'Zunehmender Halbmond', 'Gibbeuse croissante', 'Treća osmina'],
> 'full': ['Full', 'Luna piena', 'Volledig', 'Completo', 'Vollmond', 'Pleine lune', 'Pun mesec'],
> 'waning_gibbous': ['Waning Gibbous', 'Gibbosa calante', 'Zwemmende Gibbous', 'Waning Gibbous', 'Abnehmender Halbmond', 'Gibbeuse décroissante', 'Peta osmina'],
> 'third_quarter': ['Third Quarter', 'Ultimo quarto', 'Derde Kwartier', 'Tercer cuarto', 'Drittes Viertel', 'Dernier quartier', 'Treća četvrtina'],
> 'last_quarter': ['Last Quarter', 'Ultimo quarto', 'Laatste Kwartier', 'Último cuarto', 'Letztes Viertel', 'Dernier quartier', 'Zadnja četvrtina'],
> 'waning_crescent': ['Waning Crescent', 'Luna calante', 'Zwemmende sikkel', 'Waning Crescent', 'Abnehmende Sichel', 'Lune décroissante', 'Sedma osmina'],
> } ;
> `

Thanks for your help. I've released a new version that includes Serbian translation. To use it you need to specify as language: `sr-latn`.

Thanks,
Renato

**Comment by drmilos** [comment]
> 

> > Done!
> > Don't know how to embed code and hope you can use it as posted.
> > `
> > export let cwcLocale = {en: 0, it: 1, nl: 2, es: 3, de: 4, fr: 5, sr: 6};
> > export let cwcLocWindDirections = {
> > 'N': ['N', 'N', 'N', 'N', 'N', 'N', 'S'],
> > 'NNE': ['NNE', 'NNE', 'NNO', 'NNE', 'NNO', 'NNE', 'SSI'],
> > 'NE': ['NE', 'NE', 'NO', 'NE', 'NO', 'NE', 'SI'],
> > 'ENE': ['ENE', 'ENE', 'ONO', 'ENE', 'ONO', 'ENE', 'ISI'],
> > 'E': ['E', 'E', 'O', 'E', 'O', 'E', 'I'],
> > 'ESE': ['ESE', 'ESE', 'OZO', 'ESE', 'OSO', 'ESE', 'IJI'],
> > 'SE': ['SE', 'SE', 'ZO', 'SE', 'SO', 'SE', 'JI'],
> > 'SSE': ['SSE', 'SSE', 'ZZO', 'SSE', 'SSO', 'SSE', 'JJI'],
> > 'S': ['S', 'S', 'Z', 'S', 'S', 'S', 'J'],
> > 'SSW': ['SSW', 'SSO', 'ZZW', 'SSO', 'SSW', 'SSO', 'JJZ'],
> > 'SW': ['SW', 'SO', 'ZW', 'SO', 'SW', 'SO', 'JZ'],
> > 'WSW': ['WSW', 'OSO', 'WZW', 'OSO', 'WSW', 'OSO', 'ZSZ'],
> > 'W': ['W', 'O', 'W', 'O', 'W', 'O', 'Z'],
> > 'WNW': ['WNW', 'ONO', 'WNW', 'ONO', 'WNW', 'ONO', 'ZSZ'],
> > 'NW': ['NW', 'NO', 'NW', 'NO', 'NW', 'NO', 'SZ'],
> > 'NNW': ['NNW', 'NNO', 'NNW', 'NNO', 'NNW', 'NNO', 'SSZ'],
> > };
> > export let cwcTerms = {
> > 'Feels Like' : ['Feels Like', 'Percepita', 'Voelt Als', 'Parece que', 'Gefühlt', 'Ressentie', 'Subjektivni osećaj'],
> > 'new_moon': [ 'New moon', 'Novilunio', 'Nieuwe maan', 'Luna nueva', 'Neumond', 'Nouvelle lune', 'Mlad mesec'],
> > 'new': [ 'New moon', 'Novilunio', 'Nieuwe maan', 'Luna nueva', 'Neumond', 'Nouvelle lune', 'Mlad mesec'],
> > 'waxing_crescent': ['Waxing crescent', 'Luna crescente', 'Wassende sikkel', 'Media luna de cera', 'Zunehmende Sichel', 'Premier croissant', 'Premier croissant', 'Prva osmina'],
> > 'first_quarter': ['First quarter', 'Primo Quarto', 'Eerste kwartaal', 'Primer trimestre', 'Erstes Viertel', 'Premier quartier', 'Prva četvrt'],
> > 'waxing_gibbous': ['Waxing Gibbous', 'Gibbosa crescente', 'Wassen Gibbous', 'Encerado Gibbous', 'Zunehmender Halbmond', 'Gibbeuse croissante', 'Treća osmina'],
> > 'full': ['Full', 'Luna piena', 'Volledig', 'Completo', 'Vollmond', 'Pleine lune', 'Pun mesec'],
> > 'waning_gibbous': ['Waning Gibbous', 'Gibbosa calante', 'Zwemmende Gibbous', 'Waning Gibbous', 'Abnehmender Halbmond', 'Gibbeuse décroissante', 'Peta osmina'],
> > 'third_quarter': ['Third Quarter', 'Ultimo quarto', 'Derde Kwartier', 'Tercer cuarto', 'Drittes Viertel', 'Dernier quartier', 'Treća četvrtina'],
> > 'last_quarter': ['Last Quarter', 'Ultimo quarto', 'Laatste Kwartier', 'Último cuarto', 'Letztes Viertel', 'Dernier quartier', 'Zadnja četvrtina'],
> > 'waning_crescent': ['Waning Crescent', 'Luna calante', 'Zwemmende sikkel', 'Waning Crescent', 'Abnehmende Sichel', 'Lune décroissante', 'Sedma osmina'],
> > } ;
> > `
> 
> Thanks for your help. I've released a new version that includes Serbian translation. To use it you need to specify as language: `sr-latn`.
> 
> Thanks,
> Renato

I updated to latest version. Changes are there but I think you mixed sr-Latin and sr-Cyrl..
Days are on sr-Cyrl and rest of the text is sr-Latin

Days on sr-Latin shall be as following:

PON
UTO 
SRE
ČET
PET
SUB
NED

Days on sr-Cyrl are as following:
ПОН
УТО
СРЕ
ЧЕТ
ПЕТ
СУБ
НЕД

**Comment by r-renato** [comment]
This is my card using the language `sr-latn`
<img width="658" alt="Screenshot 2020-05-23 at 22 23 57" src="https://user-images.githubusercontent.com/54778313/82739945-679e8380-9d44-11ea-8f0d-7cc7d82716d3.png">
using this configuration:
```
type: custom:ha-card-weather-conditions
language: sr-latn 
```

Please, put here the screenshot of your card and the configuration.

**Comment by drmilos** [comment]
In my case something is different, or wrong.

[image: image.png]
this is the config:

animation: true
language: sr-latin
type: 'custom:ha-card-weather-conditions'

**Comment by drmilos** [comment]
I noticed now as soon as I type "sr" in language it switches to Serbian by
sr-Cyrl

**Comment by r-renato** [comment]
the language value is `sr-latn` not 'sr-latin'.

**Comment by drmilos** [comment]
[image: image.png]

**Comment by drmilos** [comment]
[image: image.png]

Solved!

That was my mistake.

Thank you
