### ISSUE TITLE
Decimals for temperature and real feel

### ISSUE THREAD

**Issue by Chompas** [r-renato/ha-card-weather-conditions#17]
Hi,

I've noticed that the temperature does not show decimal numbers and it just rounds. Is this possible?

Also, I'm using climacell and the feels_like is not being properly displayed. I think I found the problem and it's grabbing the temperature value instead.

**Comment by r-renato** [comment]
Hi. The new released version contains the fix to display the decimal numbers.

Bye,
Renato
