### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by joaopequeno-git** [r-renato/ha-card-weather-conditions#18]
I have added the component and place the resource on lovelave frontend, but when making the card nothing apperas.
Can you help?

**Comment by r-renato** [comment]
hi, put here your card config

**Comment by joaopequeno-git** [comment]
I'm using your examples but they dont work, like the one:

> type: 'custom:ha-card-weather-conditions'
uv:
  protection_window: binary_sensor.protection_window
  ozone_level: sensor.current_ozone_level
  uv_index: sensor.current_uv_index
  uv_level: sensor.current_uv_level
  max_uv_index: sensor.max_uv_index
  set_skin_type_1: sensor.skin_type_1_safe_exposure_time
  set_skin_type_2: sensor.skin_type_2_safe_exposure_time
  set_skin_type_3: sensor.skin_type_3_safe_exposure_time
  set_skin_type_4: sensor.skin_type_4_safe_exposure_time
  set_skin_type_5: sensor.skin_type_5_safe_exposure_time
  set_skin_type_6: sensor.skin_type_6_safe_exposure_time

**Comment by r-renato** [comment]
Thanks.
Can you put here also the browser console logs?

**Comment by joaopequeno-git** [comment]
> 
> 
> Thanks.
> Can you put here also the browser console logs?

Where do i found does logs?

**Comment by r-renato** [comment]
Enable the browser in development mode (see the browser menu) and find the console tab.

**Comment by joaopequeno-git** [comment]
here it goes:

> DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.e175b38b2e0a8950d69c.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.11a79aa28219a788286f.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.4c71433db7ced0e9eb8b.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.d32f3a03293fc6f3422f.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
ha-card-weather-conditions.js:372 {card_config: {…}}
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.9bf564602c90d1c05033.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
chunk.6740058f08d332da3fe0.js:2 GET https://192.168.1.200:8199/hacsfiles/themes/ios-themes/homekit-bg-dark-blue.jpg net::ERR_TOO_MANY_RETRIES
attached @ chunk.6740058f08d332da3fe0.js:2
attached @ app.3160b0f6.js:765
attached @ app.3160b0f6.js:765
attached @ app.3160b0f6.js:765
attached @ app.3160b0f6.js:765
attached @ app.3160b0f6.js:765
attached @ app.3160b0f6.js:765
connectedCallback @ app.3160b0f6.js:201
_attachDom @ app.3160b0f6.js:2
_readyClients @ app.3160b0f6.js:2
_flushClients @ app.3160b0f6.js:2
_propertiesChanged @ app.3160b0f6.js:2
_flushProperties @ app.3160b0f6.js:765
_flushProperties @ app.3160b0f6.js:2
ready @ app.3160b0f6.js:2
ready @ app.3160b0f6.js:2
ready @ app.3160b0f6.js:201
ready @ app.3160b0f6.js:201
ready @ app.3160b0f6.js:765
ready @ app.3160b0f6.js:765
ready @ app.3160b0f6.js:765
_enableProperties @ app.3160b0f6.js:765
connectedCallback @ app.3160b0f6.js:2
connectedCallback @ app.3160b0f6.js:2
connectedCallback @ app.3160b0f6.js:201
connectedCallback @ app.3160b0f6.js:201
__insert @ app.3160b0f6.js:2
__commitNode @ app.3160b0f6.js:2
__commitTemplateResult @ app.3160b0f6.js:2
commit @ app.3160b0f6.js:2
s @ app.3160b0f6.js:2
G.render @ app.3160b0f6.js:2
update @ app.3160b0f6.js:2
performUpdate @ app.3160b0f6.js:2
_enqueueUpdate @ app.3160b0f6.js:2
async function (async)
_enqueueUpdate @ app.3160b0f6.js:2
_requestUpdate @ app.3160b0f6.js:2
initialize @ app.3160b0f6.js:2
initialize @ app.3160b0f6.js:2
S @ app.3160b0f6.js:2
G @ app.3160b0f6.js:2
F @ chunk.e5bfe27b3ec84d132158.js:15
value @ chunk.cbe4ea28517972a626f9.js:3437
(anonymous) @ chunk.cbe4ea28517972a626f9.js:3437
value @ chunk.cbe4ea28517972a626f9.js:3437
value @ chunk.cbe4ea28517972a626f9.js:3437
value @ chunk.cbe4ea28517972a626f9.js:3437
performUpdate @ app.3160b0f6.js:2
_enqueueUpdate @ app.3160b0f6.js:2
async function (async)
_enqueueUpdate @ app.3160b0f6.js:2
_requestUpdate @ app.3160b0f6.js:2
initialize @ app.3160b0f6.js:2
initialize @ app.3160b0f6.js:2
S @ app.3160b0f6.js:2
G @ app.3160b0f6.js:2
i @ chunk.cbe4ea28517972a626f9.js:3425
value @ chunk.cbe4ea28517972a626f9.js:3695
(anonymous) @ chunk.cbe4ea28517972a626f9.js:3695
setTimeout (async)
(anonymous) @ chunk.cbe4ea28517972a626f9.js:725
(anonymous) @ chunk.c2bb0885de311bc3f746.js:1
requestAnimationFrame (async)
window.requestAnimationFrame @ chunk.c2bb0885de311bc3f746.js:1
i @ chunk.cbe4ea28517972a626f9.js:725
value @ chunk.cbe4ea28517972a626f9.js:3695
performUpdate @ app.3160b0f6.js:2
_enqueueUpdate @ app.3160b0f6.js:2
async function (async)
_enqueueUpdate @ app.3160b0f6.js:2
_requestUpdate @ app.3160b0f6.js:2
set @ app.3160b0f6.js:2
commit @ app.3160b0f6.js:2
commit @ app.3160b0f6.js:2
update @ app.3160b0f6.js:2
__commitTemplateResult @ app.3160b0f6.js:2
commit @ app.3160b0f6.js:2
s @ app.3160b0f6.js:2
G.render @ app.3160b0f6.js:2
update @ app.3160b0f6.js:2
performUpdate @ app.3160b0f6.js:2
_enqueueUpdate @ app.3160b0f6.js:2
async function (async)
_enqueueUpdate @ app.3160b0f6.js:2
_requestUpdate @ app.3160b0f6.js:2
set @ app.3160b0f6.js:2
value @ chunk.cbe4ea28517972a626f9.js:3812
saveConfig @ chunk.cbe4ea28517972a626f9.js:3812
value @ chunk.8cc8e3dda2dd9f37ee72.js:402
handleEvent @ app.3160b0f6.js:2
__boundHandleEvent @ app.3160b0f6.js:2
Show 5 more frames from Library code
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.e9b94afa6373698c6554.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.fd1a7bccfaf98f514133.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.0f7211fd40483e5b24d4.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.02c268a0d0b160cd3d08.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.07f5c2f58d79aaf084ed.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.9228da811cfd74c28e3f.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.eb6b0f03f43b31370215.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.f62c3af31ca0a55c9c91.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.cf7ce320d9b0df1bb6f3.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
DevTools failed to load SourceMap: Could not load content for https://192.168.1.200:8199/frontend_latest/chunk.ef4b8fafa11a896f9d3e.js.map: Certificate error: net::ERR_CERT_COMMON_NAME_INVALID
ha-card-weather-conditions.js:352 Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at ha-card-weather-conditions.js:352
    at Le (ha-card-weather-conditions.js:357)
    at HTMLElement._render (ha-card-weather-conditions.js:386)
    at HTMLElement.render (ha-card-weather-conditions.js:381)
    at HTMLElement.update (ha-card-weather-conditions.js:1)
    at HTMLElement.performUpdate (ha-card-weather-conditions.js:1)
    at HTMLElement._enqueueUpdate (ha-card-weather-conditions.js:1)

**Comment by r-renato** [comment]
Looks like not all uv sensors exist in your system. well, check and see if they do.

**Comment by joaopequeno-git** [comment]
how do i check that?

**Comment by r-renato** [comment]
this is simple, in the `ha menu` open the `developer tools` and select the `states` tab. the sensor states can be displayed here.

**Comment by joaopequeno-git** [comment]
I have installed the HACS component ald loaded at lovelace resources.
But in the states it dont whow any of this sensors.
What i'm doing wrong?
Thanks

**Comment by bsrdjan** [comment]
openuv integration configured?

**Comment by r-renato** [comment]
To configure the `openuv` integration add to your HA configuration:

```
openuv:
  api_key: !secret openuv_api_key
```

You can retrieve the key here: https://www.openuv.io/
