### ISSUE TITLE
Integrations For Air Quality data & Pollen data

### ISSUE THREAD

**Issue by AjayShanker98** [r-renato/ha-card-weather-conditions#21]
Hi, I would like to ask which air quality and pollen API do this card uses? I know uv uses openUV.

**Comment by r-renato** [comment]
The card shows only the connected sensors information. For example, the uv card section can be used with `openUV` but also with other providers processing similar information.

In any case, for `air quality` and `pollen` I use the `climacell` data provider.

**Comment by AjayShanker98** [comment]
I realized my mistake as I didn't include `air quality` and `pollen` into `ha-climacell-weather` after reading ClimaCell Developer docs.

`# Air Quality
        - co
        - epa_aqi
        - epa_health_concern
        - no2
        - o3
        - pm10
        - pm25
        - so2

#  Pollen
        - pollen_tree
        - pollen_weed
        - pollen_grass`

It is a silly mistake of mine, still learning:👍 Loving your weather card!

**Comment by AjayShanker98** [comment]
I am a student and I wanna build my own home assistant component using my government transport API. Is any tips or websites to recommend?

**Comment by r-renato** [comment]
it is not hard to create your own custom componet. To start with, see how this works: https://github.com/r-renato/ha-climacell-weather
