### ISSUE TITLE
PT Language

### ISSUE THREAD

**Issue by joaopequeno-git** [r-renato/ha-card-weather-conditions#24]
Are you interested in adding the PT Portuguese language?
If yes send me the language file to do the translations.

**Comment by r-renato** [comment]
Sure! The object to translate is the follow:

```
{
  "cwcLocWindDirections": {
    "N": "N",
    "NNE": "NNE",
    "NE": "NE",
    "ENE": "ENE",
    "E": "E",
    "ESE": "ESE",
    "SE": "SE",
    "SSE": "SSE",
    "S": "S",
    "SSW": "SSW",
    "SW": "SW",
    "WSW": "WSW",
    "W": "W",
    "WNW": "WNW",
    "NW": "NW",
    "NNW": "NNW"
  },

  "cwcTerms": {
    "Feels Like" : "Feels Like",
    "new_moon": "New moon",
    "new": "New moon",
    "waxing_crescent": "Waxing crescent",
    "first_quarter": "First quarter",
    "waxing_gibbous": "Waxing Gibbous",
    "full": "Full",
    "waning_gibbous": "Waning Gibbous",
    "third_quarter": "Third Quarter",
    "last_quarter": "Last Quarter",
    "waning_crescent": "Waning Crescent"
  }
}
```

Thanks,
Renato

**Comment by joaopequeno-git** [comment]
> 
> 
> Sure! The object to translate is the follow:
> 
> ```
> {
>   "cwcLocWindDirections": {
>     "N": "N",
>     "NNE": "NNE",
>     "NE": "NE",
>     "ENE": "ENE",
>     "E": "E",
>     "ESE": "ESE",
>     "SE": "SE",
>     "SSE": "SSE",
>     "S": "S",
>     "SSW": "SSW",
>     "SW": "SW",
>     "WSW": "WSW",
>     "W": "W",
>     "WNW": "WNW",
>     "NW": "NW",
>     "NNW": "NNW"
>   },
> 
>   "cwcTerms": {
>     "Feels Like" : "Feels Like",
>     "new_moon": "New moon",
>     "new": "New moon",
>     "waxing_crescent": "Waxing crescent",
>     "first_quarter": "First quarter",
>     "waxing_gibbous": "Waxing Gibbous",
>     "full": "Full",
>     "waning_gibbous": "Waning Gibbous",
>     "third_quarter": "Third Quarter",
>     "last_quarter": "Last Quarter",
>     "waning_crescent": "Waning Crescent"
>   }
> }
> ```
> 
> Thanks,
> Renato

Please find bellow:

`{
  "cwcLocWindDirections": {
    "N": "N",
    "NNE": "NNE",
    "NE": "NE",
    "ENE": "ENE",
    "E": "E",
    "ESE": "ESE",
    "SE": "SE",
    "SSE": "SSE",
    "S": "S",
    "SSW": "SSW",
    "SW": "SW",
    "WSW": "WSW",
    "W": "W",
    "WNW": "WNW",
    "NW": "NW",
    "NNW": "NNW"
  },

  "cwcTerms": {
    "Feels Like" : "Sentida",
    "new_moon": "Lua Nova",
    "new": "Lua nova",
    "waxing_crescent": "Lua Crescente",
    "first_quarter": "Quarto Crescente",
    "waxing_gibbous": "Crescente Gibosa",
    "full": "Lua Cheia",
    "waning_gibbous": "Minguante Gibosa",
    "third_quarter": "Quarto Minguante",
    "last_quarter": "Quarto Minguante",
    "waning_crescent": "Lua Minguante"
  }
}.`

**Comment by r-renato** [comment]
Thanks for your support. The new released version contains the pt translation.

Bye,
Renato
