### ISSUE TITLE
Add feels_like to lovelace card

### ISSUE THREAD

**Issue by clarsonJWU** [r-renato/ha-card-weather-conditions#3]
As stated in my request on the integration, it would be great to see this data added to the lovelace card. For example, my dark sky integration that I am moving away from shows the apparent temp in the following location of  a custom card

![Capture](https://user-images.githubusercontent.com/28867715/81294708-43049500-903d-11ea-8f34-235af322f60a.PNG)

**Comment by r-renato** [comment]
Ok, feels like added in the new released version.
