### ISSUE TITLE
Blank "forecast" card

### ISSUE THREAD

**Issue by h-parks** [r-renato/ha-card-weather-conditions#30]
Hi, I'm able to view the summary card just fine, but the forecast card is giving me problems.

Here's my browser console log. 

WEATHER-CONDITION-CARD  1.9.1
card-mod.js:1 CARD-MOD 1.1.0 IS INSTALLED 
:8123/local/ha-card-weather-conditions/icons/static/cloudy.svg:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ha-card-weather-conditions.js:411  WEATHER-CONDITION-CARD  1.9.1 use HACS path to retrieve icons.
ha-card-weather-conditions.js:411 Object
ha-card-weather-conditions.js:411 Object
ha-card-weather-conditions.js:429 Uncaught (in promise) TypeError: Cannot read property 'sun' of undefined
    at ha-card-weather-conditions.js:429
    at HTMLElement._render (ha-card-weather-conditions.js:443)
    at HTMLElement.render (ha-card-weather-conditions.js:420)
    at HTMLElement.update (ha-card-weather-conditions.js:1)
    at HTMLElement.performUpdate (ha-card-weather-conditions.js:1)
    at HTMLElement._enqueueUpdate (ha-card-weather-conditions.js:1)
ha-card-weather-conditions.js:411 Object
ha-card-weather-conditions.js:411 Object
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
ha-card-weather-conditions.js:411 {card_config: {…}}
weather:1 Autofocus processing was blocked because a document already has a focused element.
ha-card-weather-conditions.js:429 Uncaught (in promise) TypeError: Cannot read property 'sun' of undefined
    at ha-card-weather-conditions.js:429
    at HTMLElement._render (ha-card-weather-conditions.js:443)
    at HTMLElement.render (ha-card-weather-conditions.js:420)
    at HTMLElement.update (ha-card-weather-conditions.js:1)
    at HTMLElement.performUpdate (ha-card-weather-conditions.js:1)
    at HTMLElement._enqueueUpdate (ha-card-weather-conditions.js:1)
(anonymous) @ ha-card-weather-conditions.js:429
_render @ ha-card-weather-conditions.js:443
render @ ha-card-weather-conditions.js:420
update @ ha-card-weather-conditions.js:1
performUpdate @ ha-card-weather-conditions.js:1
_enqueueUpdate @ ha-card-weather-conditions.js:1
async function (async)
_enqueueUpdate @ ha-card-weather-conditions.js:1
_requestUpdate @ ha-card-weather-conditions.js:1
set @ ha-card-weather-conditions.js:1
value @ chunk.ac04d2743ef44195d8a3.js:858
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
commit @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
a @ app.04756a98.js:1
A.render @ app.04756a98.js:1
update @ app.04756a98.js:1
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
(anonymous) @ app.04756a98.js:40574
value @ app.04756a98.js:40574
hassChanged @ app.04756a98.js:40574
value @ app.04756a98.js:47718
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
value @ app.04756a98.js:40574
(anonymous) @ app.04756a98.js:40574
n @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1
_handleMessage @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1
ha-card-weather-conditions.js:429 Uncaught (in promise) TypeError: Cannot read property 'sun' of undefined
    at ha-card-weather-conditions.js:429
    at HTMLElement._render (ha-card-weather-conditions.js:443)
    at HTMLElement.render (ha-card-weather-conditions.js:420)
    at HTMLElement.update (ha-card-weather-conditions.js:1)
    at HTMLElement.performUpdate (ha-card-weather-conditions.js:1)
    at HTMLElement._enqueueUpdate (ha-card-weather-conditions.js:1)
(anonymous) @ ha-card-weather-conditions.js:429
_render @ ha-card-weather-conditions.js:443
render @ ha-card-weather-conditions.js:420
update @ ha-card-weather-conditions.js:1
performUpdate @ ha-card-weather-conditions.js:1
_enqueueUpdate @ ha-card-weather-conditions.js:1
async function (async)
_enqueueUpdate @ ha-card-weather-conditions.js:1
_requestUpdate @ ha-card-weather-conditions.js:1
set @ ha-card-weather-conditions.js:1
(anonymous) @ chunk.55cfcfe8bf5cea239c42.js:23460
value @ chunk.55cfcfe8bf5cea239c42.js:23460
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
value @ chunk.55cfcfe8bf5cea239c42.js:24080
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
commit @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
a @ app.04756a98.js:1
A.render @ app.04756a98.js:1
update @ app.04756a98.js:1
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
value @ app.04756a98.js:46838
value @ app.04756a98.js:43757
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
commit @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
a @ app.04756a98.js:1
A.render @ app.04756a98.js:1
update @ app.04756a98.js:1
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
commit @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
a @ app.04756a98.js:1
A.render @ app.04756a98.js:1
update @ app.04756a98.js:1
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
value @ app.04756a98.js:40574
(anonymous) @ app.04756a98.js:40574
n @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1
_handleMessage @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1
ha-card-weather-conditions.js:411 {card_config: {…}}
ha-card-weather-conditions.js:411 {card_config: {…}}
ha-card-weather-conditions.js:429 Uncaught (in promise) TypeError: Cannot read property 'sun' of undefined
    at ha-card-weather-conditions.js:429
    at HTMLElement._render (ha-card-weather-conditions.js:443)
    at HTMLElement.render (ha-card-weather-conditions.js:420)
    at HTMLElement.update (ha-card-weather-conditions.js:1)
    at HTMLElement.performUpdate (ha-card-weather-conditions.js:1)
    at HTMLElement._enqueueUpdate (ha-card-weather-conditions.js:1)
(anonymous) @ ha-card-weather-conditions.js:429
_render @ ha-card-weather-conditions.js:443
render @ ha-card-weather-conditions.js:420
update @ ha-card-weather-conditions.js:1
performUpdate @ ha-card-weather-conditions.js:1
_enqueueUpdate @ ha-card-weather-conditions.js:1
async function (async)
_enqueueUpdate @ ha-card-weather-conditions.js:1
_requestUpdate @ ha-card-weather-conditions.js:1
set @ ha-card-weather-conditions.js:1
(anonymous) @ chunk.55cfcfe8bf5cea239c42.js:23460
value @ chunk.55cfcfe8bf5cea239c42.js:23460
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
value @ chunk.55cfcfe8bf5cea239c42.js:24080
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
commit @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
a @ app.04756a98.js:1
A.render @ app.04756a98.js:1
update @ app.04756a98.js:1
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
value @ app.04756a98.js:46838
value @ app.04756a98.js:43757
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
commit @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
a @ app.04756a98.js:1
A.render @ app.04756a98.js:1
update @ app.04756a98.js:1
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
commit @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
update @ app.04756a98.js:1
__commitTemplateResult @ app.04756a98.js:1
commit @ app.04756a98.js:1
a @ app.04756a98.js:1
A.render @ app.04756a98.js:1
update @ app.04756a98.js:1
performUpdate @ app.04756a98.js:1
_enqueueUpdate @ app.04756a98.js:1
async function (async)
_enqueueUpdate @ app.04756a98.js:1
_requestUpdate @ app.04756a98.js:1
set @ app.04756a98.js:1
value @ app.04756a98.js:40574
(anonymous) @ app.04756a98.js:40574
n @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1
_handleMessage @ core.949bdaed.js:1
(anonymous) @ core.949bdaed.js:1

**Comment by r-renato** [comment]
Hi, please let see me your card configuration.

Thanks, 
Renato

**Comment by h-parks** [comment]
Certainly! I've followed your "forecast" example and your "current layer" example. 

type: custom:ha-card-weather-conditions
name: "cc_example"
language: en
animation: true
weather:
  icons_model: climacell
  forecast:
    meteogram: camera.weather2
    icons:
      day_1: sensor.cc_example_weather_condition_1d
      day_2: sensor.cc_example_weather_condition_2d
      day_3: sensor.cc_example_weather_condition_3d
      day_4: sensor.cc_example_weather_condition_4d
      day_5: sensor.cc_example_weather_condition_5d
    temperature_high:
      day_1: sensor.cc_example_temperature_max_1d
      day_2: sensor.cc_example_temperature_max_2d
      day_3: sensor.cc_example_temperature_max_3d
      day_4: sensor.cc_example_temperature_max_4d
      day_5: sensor.cc_example_temperature_max_5d
    temperature_low:
      day_1: sensor.cc_example_temperature_min_1d
      day_2: sensor.cc_example_temperature_min_2d
      day_3: sensor.cc_example_temperature_min_3d
      day_4: sensor.cc_example_temperature_min_4d
      day_5: sensor.cc_example_temperature_min_5d
    precipitation_probability:
      day_1: sensor.cc_example_precipitation_probability_1d
      day_2: sensor.cc_example_precipitation_probability_2d
      day_3: sensor.cc_example_precipitation_probability_3d
      day_4: sensor.cc_example_precipitation_probability_4d
      day_5: sensor.cc_example_precipitation_probability_5d
    precipitation_intensity:
      day_1: sensor.cc_example_precipitation_max_1d
      day_2: sensor.cc_example_precipitation_max_2d
      day_3: sensor.cc_example_precipitation_max_3d
      day_4: sensor.cc_example_precipitation_max_4d
      day_5: sensor.cc_example_precipitation_max_5d

---

type: custom:ha-card-weather-conditions
name: "cc_example"
weather:
  icons_model: climacell
  current:
    sun: sun.sun
    humidity: sensor.cc_example_humidity_percentage
    pressure: sensor.cc_example_barometric_pressure
    visibility: sensor.cc_example_visibility
    wind_bearing: sensor.cc_example_wind_direction
    wind_speed: sensor.cc_example_wind_speed
    precipitation: sensor.cc_example_precipitation
#
# Optional:
# add to display current day forecast weather
    forecast: true
  forecast:
    temperature_high:
      day_1: sensor.cc_example_temperature_max_1d
    temperature_low:
      day_1: sensor.cc_example_temperature_min_1d
    precipitation_probability:
      day_1: sensor.cc_example_precipitation_probability_1d
    precipitation_intensity:
      day_1: sensor.cc_example_precipitation_max_1d

**Comment by r-renato** [comment]
Sorry, a little bug, fixed in the new released version.
Thanks for your support.

Renato

**Comment by h-parks** [comment]
It works now, thank you! 😄
