### ISSUE TITLE
UV: Safe Exposure Times only shown in hours

### ISSUE THREAD

**Issue by h-parks** [r-renato/ha-card-weather-conditions#32]
Can we view the UV safe exposure time in minutes when it is less than 1 hour? Right now, I see '0 h' which is less helpful than '15 m'. 

![UV](https://i.imgur.com/mClbjpq.png)

**Comment by r-renato** [comment]
Hi,
this function has been added to the newly released version.

Thank you, bye
Renato

**Comment by h-parks** [comment]
Thank you!
