### ISSUE TITLE
Custom element doesn't exist: ha-card-weather-conditions

### ISSUE THREAD

**Issue by jankete** [r-renato/ha-card-weather-conditions#36]
Hi, I just installed the card (version c913ad8) via HACS (1.2.2) on my HomeAssistent (0.112.4) without error, but when I try to use it, I get the error "Custom element doesn't exist: ha-card-weather-conditions". The files are present on the system.

What might be wrong here? What and where can I have a look to get more details about the problem?

**Comment by mfabiani53** [comment]
Same here...
Here it is what i can see in the console:

![Schermata 2020-07-21 alle 19 31 34](https://user-images.githubusercontent.com/37701688/88087290-f5ea8680-cb88-11ea-8697-03d79c833510.png)

**Comment by djmirco** [comment]
Sale same😀

**Comment by mfabiani53** [comment]
Installed latest release but got nothing new...
Console says:

![Schermata 2020-07-21 alle 22 52 01](https://user-images.githubusercontent.com/37701688/88105895-eaa55400-cba4-11ea-9067-920cfd365c3f.png)

**Comment by jmutnick** [comment]
I renamed all of the *.json files to *.json1 and it now seems to work.

**Comment by joelslevy21** [comment]
> I renamed all of the *.json files to *.json1 and it now seems to work.

Didn't work for me, any chance you may have done something else? I'm also seeing the json1 not found but changing it didn't do anything

**Comment by jmutnick** [comment]
pi@home-assistant-pi4:~/.homeassistant/www/community/ha-card-weather-conditions/transl $ ls -lrt
total 64
-rw-r--r-- 1 pi pi 699 Jul 21 17:56 en.json
-rw-r--r-- 1 pi pi 747 Jul 21 17:56 fr.json
-rw-r--r-- 1 pi pi 736 Jul 21 17:56 de.json
-rw-r--r-- 1 pi pi 711 Jul 21 17:56 pt.json
-rw-r--r-- 1 pi pi 719 Jul 21 17:56 nl.json
-rw-r--r-- 1 pi pi 727 Jul 21 17:56 it.json
-rw-r--r-- 1 pi pi 714 Jul 21 17:56 sr-latn.json
-rw-r--r-- 1 pi pi 730 Jul 21 17:56 es.json
-rw-r--r-- 1 pi pi 699 Jul 21 18:08 en.json1
-rw-r--r-- 1 pi pi 727 Jul 21 18:09 it.json1
-rw-r--r-- 1 pi pi 747 Jul 21 18:10 fr.json1
-rw-r--r-- 1 pi pi 736 Jul 21 18:10 de.json1
-rw-r--r-- 1 pi pi 711 Jul 21 18:10 pt.json1
-rw-r--r-- 1 pi pi 719 Jul 21 18:10 nl.json1
-rw-r--r-- 1 pi pi 730 Jul 21 18:11 es.json1
-rw-r--r-- 1 pi pi 714 Jul 21 18:11 sr-latn.json1

This is all I did.

**Comment by lbaca** [comment]
I had the same issue. I renamed the .json files to .json1 and it still didn't work. Instead, as @jmutnick showed, I copied the files so that I have both .json and .json1 files. It still didn't work, but after restarting HA, clearing browser cache and logging back in, it's working again.

**Comment by r-renato** [comment]
I'm really sorry. It is a little bug fixed in the newly released version.

Thanks to all for your support.
Renato

**Comment by djmirco** [comment]
Thanks you Grazie a te Renato
Il 22 lug 2020, 21:09 +0200, Renato Rossi <notifications@github.com>, ha scritto:

**Comment by damousys** [comment]
Any ETA on the publication of the fix ?
According to HACS I am already on the latest version

**Comment by r-renato** [comment]
I'm really sorry. The newly released version fixed this bug.

Renato

**Comment by damousys** [comment]
Thanks, the update has fixed my problem

**Comment by jankete** [comment]
Working again with the latest version. Thanks 👍🏻
