### ISSUE TITLE
Only get an empty frame

### ISSUE THREAD

**Issue by narfel** [r-renato/ha-card-weather-conditions#38]
I get a empty canvas element without any datapoints. Latest ha and latest hacs version of this card. Is the message use HACS path to retrieve icons aimed at me? When i click it it leads to ha-card-weather-conditions.js.

![Anmerkung 2020-07-31 222537](https://user-images.githubusercontent.com/7281606/89074632-f3541200-d37c-11ea-9ded-79d0cba7922d.png)

**Comment by r-renato** [comment]
Hi,
the `weather` object is `null`, this may be due to a card configuration problem.
Please share your card configuration.

Thanks,
Renato

**Comment by narfel** [comment]
Oh my, that already helped 👍🏻 
The problem was a missing indentation of the _weather:_ block in yaml.

Thanks for your work.
