### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by boskoe** [r-renato/ha-card-weather-conditions#39]
First thank you for providing this resource.

While trying to get this installed on my Home Assistant I noticed a typo in the README.md file. In the Card Configuration section you have "use the ha-card-weather-conditionse card " when it should be "use the ha-card-weather-conditions card".
I would not have noticed it if I hadn't copied and pasted that into the HACS search field and HACS couldn't find it.

Again thanks for this.

Doug

**Comment by r-renato** [comment]
Thank you for your reporting.
It is fixed in the newly released version.

Very thanks for your support.
Renato
