### ISSUE TITLE
Not able to add more than 4 days of future forecast in lovelace card

### ISSUE THREAD

**Issue by clarsonJWU** [r-renato/ha-card-weather-conditions#4]
I currently pull in 5 days into the future for my integration (_1d, _2d, ... _5d). When I try to add more than 4 days worth of sensors into the forecast section the card does not load. I prefer seeing a 5 day forecast, if it at all possible

**Comment by r-renato** [comment]
this is a bug fixed with the new released version.

**Comment by clarsonJWU** [comment]
I was able to get the integration working, but I was referring to the new lovelace card. Though, I just went back and noticed I had an error in my yaml that was causing the issue. This can be closed. 

Thanks for your work with this new API!
