### ISSUE TITLE
sensor names wrong ?

### ISSUE THREAD

**Issue by th00mas88** [r-renato/ha-card-weather-conditions#40]
I'm not sure if I have my sensor / set up all messed up but this is how my sensors look - 

sensor.cc_example_precipitation_type
sensor.cc_example_precipitation_type_00m
sensor.cc_example_precipitation_type_0h

1 - example not test as per readme
2 - no "clear" which is "realtime" "daily" etc etc 

Any help ?

Thanks

**Comment by r-renato** [comment]
Hi,
the template for the sensors name is:
`sensor.cc_example_precipitation_type` (climacell **realtime**)
`sensor.cc_example_precipitation_type_00m` (climacell **nowcast**)
`sensor.cc_example_precipitation_type_0d` (climacell **daily**)
`sensor.cc_example_precipitation_type_0h` (climacell **hourly**)

You can found more information here: [https://github.com/r-renato/ha-climacell-weather](https://github.com/r-renato/ha-climacell-weather)

Thanks,
Renato
