### ISSUE TITLE
Ü in german locale not rendered properly

### ISSUE THREAD

**Issue by FL550** [r-renato/ha-card-weather-conditions#47]
In the german locale, the ü is not rendered properly. It shows the html code for ü instead:

![image](https://user-images.githubusercontent.com/36160004/90331796-a8aada80-dfb7-11ea-913d-34b835cdd9d4.png)

**Comment by r-renato** [comment]
Thanks for you report.
I have released a newly version that fix this bug.

Please, could you confirm that it is working fine?

Renato

**Comment by FL550** [comment]
Now it's working fine! Thank you for your quick reply!
