### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by damousys** [r-renato/ha-card-weather-conditions#5]
Is there a way to make an Dutch translation to this beautifull card ?
I can contribute with that if you have a language file or something like that

**Comment by r-renato** [comment]
Thanks, I very happy to hear this.

The card has few elements to translate. If you want you can check under Dutch translation.
```
export let cwcLocale = {en: 0, it: 1, nl: 2};

export let cwcLocWindDirections = {
  'N': ['N', 'N', 'N'],
  'NNE': ['NNE', 'NNE', 'NNO'],
  'NE': ['NE', 'NE', 'NO'],
  'ENE': ['ENE', 'ENE', 'ONO'],
  'E': ['E', 'E', 'O'],
  'ESE': ['ESE', 'ESE', 'OZO'],
  'SE': ['SE', 'SE', 'ZO'],
  'SSE': ['SSE', 'SSE', 'ZZO'],
  'S': ['S', 'S', 'Z'],
  'SSW': ['SSW', 'SSO', 'ZZW'],
  'SW': ['SW', 'SO', 'OW'],
  'WSW': ['WSW', 'OSO', 'WOW'],
  'W': ['W', 'O', 'W'],
  'WNW': ['WNW', 'ONO', 'WNW'],
  'NW': ['NW', 'NO', 'NW'],
  'NNW': ['NNW', 'NNO', 'NNW'],
};

export let cwcTerms = {
  'Feels Like' : ['Feels Like', 'Percepita', 'Voelt Als']
} ;
```

**Comment by damousys** [comment]
The first I had found already but don't now where to put it on my HASSIO installation
And the last 3 lines are new I guess

SW is West South West should be ZW
WSW is West South West should be WZW

**Comment by r-renato** [comment]
ok, thanks, fixed and released. Now you can use in language `nl`.
The new const are:

```
export let cwcLocale = {en: 0, it: 1, nl: 2};

export let cwcLocWindDirections = {
  'N': ['N', 'N', 'N'],
  'NNE': ['NNE', 'NNE', 'NNO'],
  'NE': ['NE', 'NE', 'NO'],
  'ENE': ['ENE', 'ENE', 'ONO'],
  'E': ['E', 'E', 'O'],
  'ESE': ['ESE', 'ESE', 'OZO'],
  'SE': ['SE', 'SE', 'ZO'],
  'SSE': ['SSE', 'SSE', 'ZZO'],
  'S': ['S', 'S', 'Z'],
  'SSW': ['SSW', 'SSO', 'ZZW'],
  'SW': ['SW', 'SO', 'ZW'],
  'WSW': ['WSW', 'OSO', 'WZW'],
  'W': ['W', 'O', 'W'],
  'WNW': ['WNW', 'ONO', 'WNW'],
  'NW': ['NW', 'NO', 'NW'],
  'NNW': ['NNW', 'NNO', 'NNW'],
};

export let cwcTerms = {
  'Feels Like' : ['Feels Like', 'Percepita', 'Voelt Als']
} ;
```
Tell me if it works.

**Comment by damousys** [comment]
thanks, it is working.
But where are those files located on my HASSIO installation ?
Maybe I am willing to try to build things myself
Or are those file being compiled to something while updating ?

**Comment by r-renato** [comment]
Yes, the javascript code is in your hassio.
The card source code is written in typescript (.ts), you can find it in the 'src' repository folder.

**Comment by damousys** [comment]
yea oke,
but where are the files on my installation
in **\\ha\config\www\community\ha-card-weather-conditions**
I can't find it, not even with an **sudo locate ha-cwc-consts.ts**

**Comment by r-renato** [comment]
in hassio only the javascript (.js) is present, the .ts are used to build the .js file. The build process is executed by the developer.

**Comment by damousys** [comment]
aha oke, so everything should be in the ha-card-weather-conditions.js

**Comment by r-renato** [comment]
Yes, that's right!

**Comment by damousys** [comment]
The days of the week are also dutch, but those are comming from HA I presume ?

**Comment by r-renato** [comment]
no, the days of the week are "calculated" using the javascript `date` object, `date` supports localization/translation

**Comment by damousys** [comment]
Aha oke nice
Thanks for all the info and fast service

**Comment by r-renato** [comment]
thanks to you
renato

**Comment by damousys** [comment]
what for do you need help ?

**Comment by r-renato** [comment]
I just classified this issue

**Comment by damousys** [comment]
aha oke
