### ISSUE TITLE
Night time snowy images for climacell broken

### ISSUE THREAD

**Issue by jinx8402** [r-renato/ha-card-weather-conditions#58]
ha-cwc-climacell.ts has a typo for two snowy conditions for night time. This causes a blank icon for days that have a snow condition at night:

![Screenshot_20201205-190110](https://user-images.githubusercontent.com/59454523/101267980-81c21100-372c-11eb-8974-8bf183df2048.jpg)

**Comment by r-renato** [comment]
Bug fixed. Very thanks for your report.
