### ISSUE TITLE
Add Danish language

### ISSUE THREAD

**Issue by JanHG** [r-renato/ha-card-weather-conditions#62]
Hi,

Can you add Danish (da) to the list of languages? I have listed the translation below.

{
  "cwcLocWindDirections": {
    "N": "N",
    "NNE": "NNØ",
    "NE": "NØ",
    "ENE": "ØNØ",
    "E": "Ø",
    "ESE": "ØSØ",
    "SE": "SØ",
    "SSE": "SSØ",
    "S": "S",
    "SSW": "SSV",
    "SW": "SV",
    "WSW": "VSV",
    "W": "V",
    "WNW": "VNV",
    "NW": "NV",
    "NNW": "NNV"
  },

  "cwcTerms": {
    "Feels Like" : "Føles som",
    "new_moon": "Nymåne",
    "new": "Nymåne",
    "waxing_crescent": "Tiltagende halvmåne",
    "first_quarter": "Første kvartal",
    "waxing_gibbous": "Tiltagende måne",
    "full": "Fuldmåne",
    "waning_gibbous": "Aftagende måne",
    "third_quarter": "Tredje kvartal",
    "last_quarter": "Sidste kvartal",
    "waning_crescent": "Aftagende halvmåne"
  }
}

**Comment by r-renato** [comment]
Done. Thanks for your support.
Renato

**Comment by JanHG** [comment]
Thanks but it doesn't seem to work. I have upgraded via HACS and restarted. The new da file is there but 'da' is not being recognized.
![image](https://user-images.githubusercontent.com/43895069/103954902-75730e80-5145-11eb-95eb-2de6f76ff8fa.png)

**Comment by r-renato** [comment]
sorry, I fix it.

**Comment by JanHG** [comment]
I saw you released a new version. Was it supposed to fix this? If so, then it did not work.

**Comment by r-renato** [comment]
Hi, please, show me the errors present in the browser console.

**Comment by JanHG** [comment]
Here you go. Let me know if you need more.


Some messages have been moved to the Issues panel.
ha-card-weather-conditions.js:381  WEATHER-CONDITION-CARD  1.9.6
ha-card-weather-conditions.js:381  WEATHER-CONDITION-CARD  1.9.6 use HACS path to retrieve icons.
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:270 Icons issue. States: icons_model=defaulthass - isDay=false - condition: unknown.
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
chunk.455e79b014618741a716.js:2837 card custom:ha-card-weather-conditions SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLElement.setConfig (ha-card-weather-conditions.js:381)
    at s (chunk.455e79b014618741a716.js:2837)
    at chunk.455e79b014618741a716.js:2837
    at d (chunk.455e79b014618741a716.js:2837)
    at c (chunk.455e79b014618741a716.js:2837)
    at a (chunk.455e79b014618741a716.js:2837)
    at HTMLElement.value (chunk.72df0e2934b88fac4ebc.js:1)
    at HTMLElement.value (chunk.72df0e2934b88fac4ebc.js:1)
    at HTMLElement.performUpdate (app.924deda6.js:10297)
c @ chunk.455e79b014618741a716.js:2837
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
chunk.455e79b014618741a716.js:2837 card custom:ha-card-weather-conditions SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLElement.setConfig (ha-card-weather-conditions.js:381)
    at s (chunk.455e79b014618741a716.js:2837)
    at chunk.455e79b014618741a716.js:2837
    at d (chunk.455e79b014618741a716.js:2837)
    at c (chunk.455e79b014618741a716.js:2837)
    at a (chunk.455e79b014618741a716.js:2837)
    at HTMLElement.value (chunk.72df0e2934b88fac4ebc.js:1)
    at HTMLElement.value (chunk.72df0e2934b88fac4ebc.js:1)
    at HTMLElement.performUpdate (app.924deda6.js:10297)
c @ chunk.455e79b014618741a716.js:2837
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 Object
chunk.455e79b014618741a716.js:2837 card custom:ha-card-weather-conditions SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLElement.setConfig (ha-card-weather-conditions.js:381)
    at s (chunk.455e79b014618741a716.js:2837)
    at chunk.455e79b014618741a716.js:2837
    at d (chunk.455e79b014618741a716.js:2837)
    at c (chunk.455e79b014618741a716.js:2837)
    at a (chunk.455e79b014618741a716.js:2837)
    at HTMLElement.value (chunk.72df0e2934b88fac4ebc.js:1)
    at HTMLElement.value (chunk.72df0e2934b88fac4ebc.js:1)
    at HTMLElement.performUpdate (app.924deda6.js:10297)
c @ chunk.455e79b014618741a716.js:2837
ha-card-weather-conditions.js:381 Object
ha-card-weather-conditions.js:381 {card_config: {…}}
ha-card-weather-conditions.js:381 {card_config: {…}}
ha-card-weather-conditions.js:381 {card_config: {…}}
ha-card-weather-conditions.js:381 {card_config: {…}}
ha-card-weather-conditions.js:381 {card_config: {…}}
chunk.455e79b014618741a716.js:2837 card custom:ha-card-weather-conditions SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLElement.setConfig (ha-card-weather-conditions.js:381)
    at s (chunk.455e79b014618741a716.js:2837)
    at chunk.455e79b014618741a716.js:2837
    at d (chunk.455e79b014618741a716.js:2837)
    at c (chunk.455e79b014618741a716.js:2837)
    at a (chunk.455e79b014618741a716.js:2837)
    at HTMLElement.value (chunk.72df0e2934b88fac4ebc.js:1)
    at HTMLElement.value (chunk.72df0e2934b88fac4ebc.js:1)
    at HTMLElement.performUpdate (app.924deda6.js:10297)
c @ chunk.455e79b014618741a716.js:2837
a @ chunk.455e79b014618741a716.js:2837
value @ chunk.72df0e2934b88fac4ebc.js:1
value @ chunk.72df0e2934b88fac4ebc.js:1
performUpdate @ app.924deda6.js:10297
_enqueueUpdate @ app.924deda6.js:10297
async function (async)
_enqueueUpdate @ app.924deda6.js:10297
requestUpdateInternal @ app.924deda6.js:10297
set @ app.924deda6.js:10297
commit @ app.924deda6.js:10297
commit @ app.924deda6.js:10297
update @ app.924deda6.js:10297
__commitTemplateResult @ app.924deda6.js:10297
commit @ app.924deda6.js:10297
a @ app.924deda6.js:10297
H.render @ app.924deda6.js:10297
update @ app.924deda6.js:10297
performUpdate @ app.924deda6.js:10297
_enqueueUpdate @ app.924deda6.js:10297
async function (async)
_enqueueUpdate @ app.924deda6.js:10297
requestUpdateInternal @ app.924deda6.js:10297
set @ app.924deda6.js:10297
value @ chunk.40d04e67f9984ebf876b.js:954
handleEvent @ app.924deda6.js:10297
__boundHandleEvent @ app.924deda6.js:10297
i @ app.924deda6.js:10297
value @ chunk.1ea6ef6c0d2b8e9fc07f.js:615
value @ chunk.1ea6ef6c0d2b8e9fc07f.js:615
value @ chunk.1ea6ef6c0d2b8e9fc07f.js:981
handleEvent @ app.924deda6.js:10297
__boundHandleEvent @ app.924deda6.js:10297
i @ app.924deda6.js:10297
value @ chunk.6e5a836a6bab6fc2d183.js:1
(anonymous) @ chunk.6e5a836a6bab6fc2d183.js:1
ve @ chunk.6dd565de1dd2dfd0be8c.js:1
Ai @ chunk.6dd565de1dd2dfd0be8c.js:1
Mi @ chunk.6dd565de1dd2dfd0be8c.js:1
(anonymous) @ chunk.6dd565de1dd2dfd0be8c.js:1
Lr @ chunk.6dd565de1dd2dfd0be8c.js:1
Si @ chunk.6dd565de1dd2dfd0be8c.js:1
Di @ chunk.6dd565de1dd2dfd0be8c.js:1
os.poll @ chunk.6dd565de1dd2dfd0be8c.js:1
(anonymous) @ chunk.6dd565de1dd2dfd0be8c.js:1

**Comment by r-renato** [comment]
Please, install the last version and check the card again. For me working fine.

**Comment by JanHG** [comment]
I did a reinstall but still face the same issue. Other languages work fine so it is something with the Danish...

**Comment by r-renato** [comment]
please, put here the browser console logs.

**Comment by JanHG** [comment]
[1610319840249.log](https://github.com/r-renato/ha-card-weather-conditions/files/5793461/1610319840249.log)

Clicking all the "Chunk." links give:
"Could not load content for webpack://home-assistant-frontend/chunk.455e79b014618741a716.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)"

**Comment by r-renato** [comment]
umm.. try to clear the browser cache

**Comment by JanHG** [comment]
Not sure what happened but the upgrade to the second release of today fixed it. Thanks.
