### ISSUE TITLE
Norwegian language added to repo

### ISSUE THREAD

**Issue by palengh** [r-renato/ha-card-weather-conditions#63]
Hi, there!

I have committed a new language file for Norwegian. Please accept it and update the language list of available languages.
Best regards

Pål Engh

**Comment by r-renato** [comment]
Hi Pål, I don't have any pull request.

**Comment by palengh** [comment]
Hmmm...
I am new to Github. here is my Norwegian translation.

{
  "cwcLocWindDirections": {
    "N": "N",
    "NNE": "NNØ",
    "NE": "NØ",
    "ENE": "ØNØ",
    "E": "Ø",
    "ESE": "ØSØ",
    "SE": "SØ",
    "SSE": "SSØ",
    "S": "S",
    "SSW": "SSV",
    "SW": "SV",
    "WSW": "VSV",
    "W": "V",
    "WNW": "VNV",
    "NW": "NV",
    "NNW": "NNV"
  },

  "cwcTerms": {
    "Feels Like" : "Føles som",
    "new_moon": "Nymåne",
    "new": "Nymåne",
    "waxing_crescent": "Tiltagende halvmåne",
    "first_quarter": "Første kvartal",
    "waxing_gibbous": "Tiltagende måne",
    "full": "Fullmåne",
    "waning_gibbous": "Avtagende måne",
    "third_quarter": "Tredje kvartal",
    "last_quarter": "Sidste kvartal",
    "waning_crescent": "Avtagende halvmåne"
  }
}

**Comment by r-renato** [comment]
Done, you can try to use it.

**Comment by palengh** [comment]
I see you have used no-NO as language identification for the file. However, "no" is the ISO 639-1 code for Norwegian.
And using `language: no-NO` still displays English text, even after updating the ad-on in HACS.

**Comment by r-renato** [comment]
Sorry, a little issue fixed with the new released version.

**Comment by palengh** [comment]
Now it works with `language: no-NO` Any chance you make it `language: no`?

**Comment by r-renato** [comment]
I prefer to use the double notation, this simplifies the card configuration.

Thank you, 
Renato
