### ISSUE TITLE
Icon centered

### ISSUE THREAD

**Issue by RenzoBeux** [r-renato/ha-card-weather-conditions#7]
Hi, sorry its me again, is there any way to make icon centered when no other info is displayed?
Also, could this card be used as a button, so when presed navigate to another tab?
Thank you!
(If i can be of help in any way tell me please)
![image](https://user-images.githubusercontent.com/47984043/81859493-b3c71800-953b-11ea-96cb-d211b2cb0881.png)

**Comment by r-renato** [comment]
you can override the css card. for example:

```
              - type: custom:ha-card-weather-conditions
                style: |
                  ha-card {
                    background: white;
                  }
                  .icon.bigger {
                      left: 2em !important;
                  }
                language: it
                animation: false
                weather:
```

**Comment by RenzoBeux** [comment]
That works, yes, i tried that but didnt know how to point to the icon.bigger element. And to make it work also as a button do you have any workarround?
Thank you very much and sorry for being asking newby questions!

**Comment by mfabiani53** [comment]
Ti scrivo qui perchè proprio non so come contattarti direttamente.
Ho provato ad inserire la scheda relativa agli UV inserendo i sensori nella card, ma non ho capito come fare per ottenerli. Basta aggiungere -uv fra le condizioni monitorate in sensor.yaml?

**Comment by r-renato** [comment]
ciao,
devi utilizzare l'integrazione openuv. Questo è un esempio:

```
openuv:
  api_key: !secret openuv_api_key
```

Poi puoi inserire i sensori nella card.

**Comment by r-renato** [comment]
> That works, yes, i tried that but didnt know how to point to the icon.bigger element. And to make it work also as a button do you have any workarround?
> Thank you very much and sorry for being asking newby questions!

This card does not work as a button. What kind of action do you need?

**Comment by mfabiani53** [comment]
Scusami, dove trovo l'integrazione openuv?

**Comment by r-renato** [comment]
si

**Comment by RenzoBeux** [comment]
> > That works, yes, i tried that but didnt know how to point to the icon.bigger element. And to make it work also as a button do you have any workarround?
> > Thank you very much and sorry for being asking newby questions!
> 
> This card does not work as a button. What kind of action do you need?

Navigation to another tab, cause i have this small card showing basic info, and when pressed is intended to open a tab containing all info about weather. I will think a workarround

**Comment by RenzoBeux** [comment]
PD: styling works perfectly, thanks for that!

**Comment by r-renato** [comment]
> Navigation to another tab, cause i have this small card showing basic info, and when pressed is intended to open a tab containing all info about weather. I will think a workarround

You can try using the button card plugin ([https://github.com/custom-cards/button-card](https://github.com/custom-cards/button-card)), it might be useful for you.
