### ISSUE TITLE
openweathermap - missing icons

### ISSUE THREAD

**Issue by Warter21** [r-renato/ha-card-weather-conditions#71]
Hi,

Thanks for you great work!

The icons are missing if I set the icon_models to openweathermap.

I have also two questions:
How can I configure the 5 days forecast with openweathermap?
Is it possible to create a separate package for OpenUV?

Regards,
Warter

**Comment by polonezkombi** [comment]
How can I configure the 5 days forecast with openweathermap? -> through restAPI, basically creating separate sensors for each value (min, max, %, mm/h)

Is it possible to create a separate package for OpenUV? -> yes, same way
