### ISSUE TITLE
Forecast showing as 80 % / Na mm/h

### ISSUE THREAD

**Issue by sunsgs** [r-renato/ha-card-weather-conditions#8]
Ciao (italiano anche io)
the forecast is showing as 80 % / Na mm/h

**Comment by r-renato** [comment]
ehi ciao, na (not available) indica che il sensore non sta fornendo alcun dato. comunque posta una immagine così capisco meglio.

Grazie mille, ciao.
Renato

**Comment by sunsgs** [comment]
Ciao e scusa per il ritardo
<img width="368" alt="Screenshot 2020-05-25 at 18 47 05" src="https://user-images.githubusercontent.com/1398055/82831237-2b8c2f80-9eb8-11ea-8800-c7c66f34a793.png">

**Comment by r-renato** [comment]
Grazie. Verifica se lo stato del sensore ha un valore e nel caso controlla anche se il nome del sensore è scritto bene nella configurazione della scheda.

**Comment by sunsgs** [comment]
animation: true
language: en
type: 'custom:ha-card-weather-conditions'
weather:
  current:
    current_conditions: sensor.climacell_weather_condition
    forecast: true
    sun: sun.sun
    temperature: sensor.climacell_temperature
  forecast:
    icons:
      day_1: sensor.climacell_weather_condition_0d
      day_2: sensor.climacell_weather_condition_1d
      day_3: sensor.climacell_weather_condition_2d
      day_4: sensor.climacell_weather_condition_3d
      day_5: sensor.climacell_weather_condition_4d
    precipitation_probability:
      day_1: sensor.climacell_precipitation_probability_0d
      day_2: sensor.climacell_precipitation_probability_1d
      day_3: sensor.climacell_precipitation_probability_2d
      day_4: sensor.climacell_precipitation_probability_3d
      day_5: sensor.climacell_precipitation_probability_4d
    temperature_high:
      day_1: sensor.climacell_max_temperature_0d
      day_2: sensor.climacell_max_temperature_1d
      day_3: sensor.climacell_max_temperature_2d
      day_4: sensor.climacell_max_temperature_3d
      day_5: sensor.climacell_max_temperature_4d
    temperature_low:
      day_1: sensor.climacell_min_temperature_0d
      day_2: sensor.climacell_min_temperature_1d
      day_3: sensor.climacell_min_temperature_2d
      day_4: sensor.climacell_min_temperature_3d
      day_5: sensor.climacell_min_temperature_4d
  icons_model: climacell

questa è la mia card, non capisco dove sbaglio. 
Inoltre, volessi implementare anche i feels_like, come faccio?

**Comment by r-renato** [comment]
ciao, sembra un un problema di formattazione, `type: custom:ha-card-weather-conditions` va in testa. copiati un esempio e fai attenzione all'indentazione. ;)

Renato

**Comment by damousys** [comment]
I have the same problem here is my code 

animation: true
language: nl
type: 'custom:ha-card-weather-conditions'
weather:
  current:
    current_conditions: sensor.cc_cc_weather_condition
    feels_like: sensor.cc_cc_feels_like
    forecast: true
    humidity: sensor.cc_cc_humidity_percentage
    precipitation: sensor.cc_cc_precipitation
    precipitation_type: sensor.cc_cc_precipitation_type
    pressure: sensor.cc_cc_barometric_pressure
    sun: sun.sun
    temperature: sensor.cc_cc_temperature_0d
    visibility: sensor.cc_cc_visibility
    wind_bearing: sensor.cc_cc_wind_direction
    wind_speed: sensor.cc_cc_wind_speed
  forecast:
    icons:
      day_1: sensor.cc_cc_weather_condition
      day_2: sensor.cc_cc_weather_condition_1d
      day_3: sensor.cc_cc_weather_condition_2d
      day_4: sensor.cc_cc_weather_condition_3d
      day_5: sensor.cc_cc_weather_condition_4d
      day_6: sensor.cc_cc_weather_condition_5d
    meteogram: camera.vught
    precipitation_intensity:
      day_1: sensor.sensor.cc_cc_precipitation_maximum_0d
      day_2: sensor.sensor.cc_cc_precipitation_maximum_1d
      day_3: sensor.sensor.cc_cc_precipitation_maximum_2d
      day_4: sensor.sensor.cc_cc_precipitation_maximum_3d
      day_5: sensor.sensor.cc_cc_precipitation_maximum_4d
      day_6: sensor.sensor.cc_cc_precipitation_maximum_5d
    precipitation_probability:
      day_1: sensor.cc_cc_precipitation_probability_0d
      day_2: sensor.cc_cc_precipitation_probability_1d
      day_3: sensor.cc_cc_precipitation_probability_2d
      day_4: sensor.cc_cc_precipitation_probability_3d
      day_5: sensor.cc_cc_precipitation_probability_4d
      day_6: sensor.cc_cc_precipitation_probability_5d
    temperature_high:
      day_1: sensor.cc_cc_temperature_maximum_1d
      day_2: sensor.cc_cc_temperature_maximum_1d
      day_3: sensor.cc_cc_temperature_maximum_2d
      day_4: sensor.cc_cc_temperature_maximum_3d
      day_5: sensor.cc_cc_temperature_maximum_4d
      day_6: sensor.cc_cc_temperature_maximum_5d
    temperature_low:
      day_1: sensor.cc_cc_temperature_minimum_0d
      day_2: sensor.cc_cc_temperature_minimum_1d
      day_3: sensor.cc_cc_temperature_minimum_2d
      day_4: sensor.cc_cc_temperature_minimum_3d
      day_5: sensor.cc_cc_temperature_minimum_4d
      day_6: sensor.cc_cc_temperature_minimum_5d
  icons_model: climacell
