### ISSUE TITLE
Blank card with moon_phase

### ISSUE THREAD

**Issue by KibosJ** [r-renato/ha-card-weather-conditions#9]
Since updating HA-Core to 0.110.0 I noticed that my card was missing.

I removed `moon_phase: sensor.cc_moon_phase` and the card works again, but as soon as I add this back in to the configuration the card goes blank and breaks.

I can't see any log entries and I have cleared the cache to no avail. The screenshot shows the top card without `moon_phase: sensor.cc_moon_phase` and the bottom one with it

<img width="499" alt="Screenshot 2020-05-21 at 08 15 57" src="https://user-images.githubusercontent.com/29429479/82533552-677f6780-9b3b-11ea-9eeb-6919c1cc3628.png">

**Comment by r-renato** [comment]
Thanks, the bug is fixed in the new released version.

Bye, Renato
