### ISSUE TITLE
Custom element doesn't exist: ha-card-weather-conditions.

### ISSUE THREAD

**Issue by mitch55500** [r-renato/ha-card-weather-conditions#94]
Hi everyone, 

My configuration : 
![image](https://user-images.githubusercontent.com/31507239/174910233-3f7db5be-8401-4543-a3d5-89d0cbc7887d.png)

I can't install this card.
Here what I get : 
![image](https://user-images.githubusercontent.com/31507239/174909966-88e5ea40-ae10-4185-813d-0b1695116844.png)

And the console of my browser : 
![image](https://user-images.githubusercontent.com/31507239/175037797-faf698fc-06eb-4d81-b003-5b9d65e098bb.png)

Do you know what is the problem?

**Comment by mitch55500** [comment]
@r-renato , any idea?

**Comment by enazevedo** [comment]
@mitch55500 , not sure if it is the same issue I had, but I faced this, and a re-install on HACS fixed.
(although I have a different problem now, but I will not blow this thread :) )

**Comment by mitch55500** [comment]
@enazevedo, it works now.
Thanks.

I close.
